Dir.chdir(name)
`make clean`

# generate instructions.c
require 'psych'
instructions = Psych.load(open 'ruby/requests.yaml')
File.open('requests.h', 'w') do |file|
  file.puts "// Instructions autogenerated from contents of instructions.yaml when compile.hex.rb is run"
  instructions.each do |key, value|
    file.puts "#define #{key} #{value}"
  end
end

`env SPEED=#{speed} DEVICE=#{mmcu} make main.hex`
raise "failed!" unless $? == 0
`cp main.hex firmware.hex`
Dir.chdir('..')
