// Instructions autogenerated from contents of instructions.yaml when compile.hex.rb is run
#define set_pulse_code 5
#define get_pulse_code 6
#define get_pulse_code_length 7
#define send_pulse_code 10
#define set_broadcasting_gap 16
#define get_broadcasting_gap 17
#define get_cpu_frequency 18
#define set_broadcasting_frequency 19
#define get_broadcasting_frequency 20
#define set_indicator 32
#define get_indicator 33
#define set_indicator_luminance 34
#define get_indicator_luminance 35
#define set_indicator_as_debug_light 36
